name: NPM Package Security Workflow

on: [push]

jobs:
    scan:
        name: npm audit
        runs-on: ubuntu-20.04
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        steps:
            - uses: actions/checkout@v2
            - name: install dependencies
              run: npm ci
            - uses: oke-py/npm-audit-actions@v1.6.0
              with:
                    audit_level: moderate
                    issue_assignees: oke-py
                    issue_labels: vulnerability, test
                    dedupe_issues: true
